package apresentacao;

import static logicajogo.Elemento.*;

import java.io.FileNotFoundException;

import logicajogo.Elemento;
import logicajogo.MapaGlobal;
import logicajogo.Mapa;
import logicajogo.Tabuleiro;

public class Main {

	public static void main(String[] args) throws FileNotFoundException {
		// Construção do Mapa do Jogo
		// Mapa Inicial
		final Elemento[][] mapa1 = {
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,              AGUA,  AGUA,         AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,              AGUA,  AGUA,         AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  TERRA,  TERRA, TERRA, TERRA, TERRA, TERRA,            TERRA, TERRA,        TERRA, TERRA, TERRA, TERRA, TERRA,  AGUA},
				{TERRA,  TERRA, TERRA, TERRA, TERRA, TERRA, TERRA,            TERRA, PORTAL, TERRA, TERRA, TERRA, TERRA, TERRA, TERRA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, PLACA,            GRAMA, GRAMA,        GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, PEDRA, PEDRA,             PEDRA, GRAMA,        GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
				{GRAMA, GRAMA, VIDA, GRAMA, PEDRA, PEDRA, PERSONAGEM_CIMA_PEDRA, PEDRA, PEDRA,        GRAMA, GRAMA, GRAMA, GRAMA, RUBI,  GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, PEDRA, PEDRA, PEDRA,             PEDRA, PEDRA,        GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
				{GRAMA, GRAMA, RUBI,  GRAMA, GRAMA, PEDRA, PEDRA,             PEDRA, GRAMA,        GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
		};
		// Mapa Inicial Esquerda
		final Elemento[][] mapa2 = {
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  PEDRA,  AGUA,         AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  PEDRA,  AGUA,         AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  AGUA,  AGUA, AGUA, AGUA, TERRA, TERRA,PEDRA, TERRA,        TERRA, TERRA, TERRA, TERRA, TERRA,  AGUA},
				{AGUA,  AGUA, AGUA, AGUA, TERRA, TERRA, TERRA,PEDRA, PEDRAENFEITE, TERRA, TERRA, TERRA, TERRA, TERRA, TERRA},
				{AGUA, AGUA, AGUA, TERRA, TERRA, TERRA, TERRA, PEDRA, TERRA,        TERRA, TERRA, TERRA, TERRA, TERRA, PERSONAGEM_ESQUERDA_GRAMA},
				{AGUA, AGUA, TERRA, TERRA, TERRA, TERRA, TERRA, PEDRA, TERRA,        TERRA, TERRA, TERRA, TERRA, GRAMA, GRAMA},
				{AGUA, AGUA, TERRA, TERRA, TERRA, TERRA, TERRA, PEDRA, PEDRA,        PEDRA, PEDRA, PEDRA, PEDRA, RUBI,  GRAMA},
				{AGUA, AGUA, TERRA, TERRA, TERRA, TERRA, TERRA, PEDRA, TERRA,        TERRA, TERRA, GRAMA, GRAMA, GRAMA, GRAMA},
				{AGUA, AGUA, RUBI,  TERRA, TERRA, TERRA, TERRA, PEDRA, TERRA,        TERRA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
		};
		// Mapa Inicial Esquerda -> CIMA
		final Elemento[][] mapa3 = {
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,               AGUA,  AGUA, AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA,               AGUA,  AGUA, AGUA,  AGUA,  AGUA,  AGUA,  AGUA,  AGUA},
				{AGUA,  AGUA,  AGUA, AGUA, AGUA, AGUA, TERRA,PASSAGEM,             TERRA, AGUA, AGUA, AGUA, AGUA, AGUA,  AGUA},
				{AGUA,  AGUA, AGUA, AGUA, AGUA, AGUA, PLACA,PEDRA,              TERRA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, PEDRA,              AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, PEDRA,              AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, PEDRA,              AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, PEDRA,              AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{AGUA, AGUA, AGUA,  AGUA, AGUA, AGUA, AGUA, PERSONAGEM_CIMA_PEDRA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
		};
		// Mapa Inicial Esquerda -> CIMA.Caverna
		final Elemento[][] mapa3Caverna = {
				{PAREDE_CAVERNA_CANTO_SUPERIOR_ESQUERDO,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR, PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR, PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_MEIO_SUPERIOR,  PAREDE_CAVERNA_CANTO_SUPERIOR_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO,  VIDA,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1, TERRA_CAVERNA1,  TERRA_CAVERNA1, TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  TERRA_CAVERNA1,  PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO,  TERRA_CAVERNA1,  TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1,TERRA_CAVERNA1,TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1,  PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO,  TERRA_CAVERNA1, TERRA_CAVERNA1, LAVA, LAVA, LAVA, LAVA,TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO, TERRA_CAVERNA1, TERRA_CAVERNA1, LAVA, LAVA, LAVA, LAVA, LAVA, LAVA, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO, TERRA_CAVERNA1, TERRA_CAVERNA1, LAVA, LAVA, LAVA, LAVA, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_MEIO_ESQUERDO, TERRA_CAVERNA1, TERRA_CAVERNA1, PERSONAGEM_CIMA_TERRA_CAVERNA, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, TERRA_CAVERNA1, PAREDE_CAVERNA_MEIO_DIREITO},
				{PAREDE_CAVERNA_CANTO_INFERIOR_ESQUERDO, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR,  PASSAGEMVOLTA, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_MEIO_INFERIOR, PAREDE_CAVERNA_CANTO_INFERIOR_DIREITO},
		};
		Mapa mapaInicial = new Mapa(mapa1);
		mapaInicial.adicionarMensagemMapa("<html> <font color='blue'> Seja Bem-Vindo</font> ao <font color='red'>LINK GAMES</font>"
				+ "<br> <br>OBJETIVOS: <font color='green'> <br>-> Coletar Rubis <br>"
				+ " -> Encontrar a Chave do Portal </font><br><br>"
				+ "<font color='orange'> BOA SORTE!</font> </html>",new FabricaIcones().obterIcone(PERSONAGEM_BAIXO_GRAMA));
		Mapa mapaInicialEsquerda = new Mapa(mapa2);
		Mapa mapaInicialEsquerdaCima = new Mapa(mapa3);
		mapaInicialEsquerdaCima.adicionarMensagemMapa("<html> <font color='red'> ATENÇÃO!</font>"
				+ "<br> <br>A Caverna a Seguir é Considerada uma Caverna PERIGOSA!",new FabricaIcones().obterIcone(PASSAGEM));
		mapaInicialEsquerdaCima.adicionarMapas(mapa3Caverna);
		
		MapaGlobal estruturaMapaIncial = new MapaGlobal(mapaInicial);
		estruturaMapaIncial.adicionarMapaEsquerda(mapaInicialEsquerda);
		estruturaMapaIncial.getMapaEsquerda().adicionarMapaCima(mapaInicialEsquerdaCima);
		
		Tabuleiro tabuleiro = new Tabuleiro(estruturaMapaIncial,5);
		tabuleiro.setSaida(new TelaJogo(tabuleiro, new FabricaIcones()));
		tabuleiro.iniciarJogo();
		
	}
}
